/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ascii2ebcdic;

import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ciazhar
 */
public class Ascii2ebcdicform extends javax.swing.JFrame {

    /**
     * Creates new form Ascii2ebcdicform
     */
    public Ascii2ebcdicform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        awalEbcdic = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        awalAscii = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilAscii = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        hasilEbcdic = new javax.swing.JTextArea();
        asciiButton = new javax.swing.JButton();
        ebcdicButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        awalEbcdic.setColumns(20);
        awalEbcdic.setRows(5);
        jScrollPane1.setViewportView(awalEbcdic);

        awalAscii.setColumns(20);
        awalAscii.setRows(5);
        jScrollPane2.setViewportView(awalAscii);

        jLabel1.setText("ASCII to EBCDIC");

        hasilAscii.setColumns(20);
        hasilAscii.setRows(5);
        jScrollPane3.setViewportView(hasilAscii);

        hasilEbcdic.setColumns(20);
        hasilEbcdic.setRows(5);
        jScrollPane4.setViewportView(hasilEbcdic);

        asciiButton.setText("Ubah");
        asciiButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asciiButtonMouseClicked(evt);
            }
        });

        ebcdicButton.setText("Ubah");
        ebcdicButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ebcdicButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("EBCDIC ke ASCII");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ebcdicButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(asciiButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(asciiButton)))
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(ebcdicButton))
                    .addComponent(jScrollPane4))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String toBinary( byte[] bytes )
    {
        StringBuilder sb = new StringBuilder(bytes.length * Byte.SIZE);
        for( int i = 0; i < Byte.SIZE * bytes.length; i++ ){
            sb.append((bytes[i / Byte.SIZE] << i % Byte.SIZE & 0x80) == 0 ? '0' : '1');    
        }
        sb.append(" ");
        return sb.toString();
    }
    private void asciiButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asciiButtonMouseClicked
        try {
            String kode = awalAscii.getText();
            byte[] ascii = kode.getBytes("ASCII");
            String ebcdic = new String(ascii,"Cp1047");
            String biner =  toBinary(ascii);
            
            hasilAscii.setText("biner : "+biner+"\nebcdic : "+ebcdic);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Ascii2ebcdicform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asciiButtonMouseClicked

    private void ebcdicButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ebcdicButtonMouseClicked
        try {
            String kode = awalEbcdic.getText();
            byte[] ebcdic = kode.getBytes("Cp1047");
            String ascii = new String(ebcdic,"ASCII");
            String biner =  toBinary(ebcdic);
            
            
            hasilEbcdic.setText("biner : "+biner+"\nascii : "+ascii);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(Ascii2ebcdicform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ebcdicButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ascii2ebcdicform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ascii2ebcdicform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ascii2ebcdicform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ascii2ebcdicform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ascii2ebcdicform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asciiButton;
    private javax.swing.JTextArea awalAscii;
    private javax.swing.JTextArea awalEbcdic;
    private javax.swing.JButton ebcdicButton;
    private javax.swing.JTextArea hasilAscii;
    private javax.swing.JTextArea hasilEbcdic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
